#!/usr/bin/env python
import sys

input_source = sys.stdin
solution_set = '../../data/solution/dev_solution'

num_correct = 0
total = 0
for l1, l2 in zip(open(solution_set), input_source):
  total = total + 1
  if l1 == l2:
    num_correct = num_correct + 1

print "Precision: ", (num_correct / float(total))